### ISSUE TITLE
使用 Nginx Proxy Manager 进行反代的基本步骤

### ISSUE THREAD

**Issue by meektion** [meektion/meektion.github.io#20]
Nginx Proxy Manager（NPM）是一个基于 Nginx 的图形化管理工具，用于轻松配置反向代理、SSL 证书、负载均衡等。它提供了一个用户友好的 Web 界面，使得管理 Nginx 配置变得更加简单。

### 使用 Nginx Proxy Manager 进行反代的基本步骤

1. **安装 Nginx Proxy Manager**
   - 你可以通过 Docker 来安装 Nginx Proxy Manager。以下是一个简单的 Docker Compose 配置文件示例：

     ```yaml
     version: '3'
     services:
       app:
         image: 'jc21/nginx-proxy-manager:latest'
         restart: unless-stopped
         ports:
           - '80:80'
           - '81:81'
           - '443:443'
         volumes:
           - ./data:/data
           - ./letsencrypt:/etc/letsencrypt
     ```

   - 保存为 `docker-compose.yml` 文件后，运行 `docker-compose up -d` 启动服务。

2. **访问管理界面**
   - Nginx Proxy Manager 的管理界面默认运行在 `81` 端口。打开浏览器，访问 `http://<your-server-ip>:81`。
   - 默认的用户名和密码是 `admin@example.com` 和 `changeme`。首次登录后建议修改密码。

3. **添加反向代理**
   - 登录后，点击 "Proxy Hosts" -> "Add Proxy Host"。
   - 在 "Details" 选项卡中：
     - **Domain Names**: 输入你要代理的域名，例如 `example.com`。
     - **Scheme**: 选择 `http` 或 `https`，取决于你的后端服务。
     - **Forward Hostname/IP**: 输入你要代理的后端服务的 IP 或域名。
     - **Forward Port**: 输入后端服务的端口。
   - 在 "SSL" 选项卡中，你可以选择自动申请 Let's Encrypt 的 SSL 证书，或者上传自定义的 SSL 证书。
   - 点击 "Save" 保存配置。

4. **测试反向代理**
   - 配置完成后，你可以通过访问 `http://example.com` 或 `https://example.com` 来测试反向代理是否正常工作。

### 其他功能

- **SSL 证书管理**: Nginx Proxy Manager 支持自动申请和续期 Let's Encrypt 的 SSL 证书。
- **访问控制**: 你可以配置基本的 HTTP 认证，限制特定 IP 访问等。
- **负载均衡**: 支持简单的负载均衡配置。

### 注意事项

- 确保你的域名 DNS 已经正确解析到服务器的 IP 地址。
- 如果你使用的是云服务提供商（如 AWS、GCP、Azure 等），确保安全组或防火墙规则允许 HTTP/HTTPS 流量通过。

通过 Nginx Proxy Manager，你可以轻松地管理和配置反向代理，而无需手动编辑复杂的 Nginx 配置文件。
